name: Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set QGis docker container
        run: docker pull qgis/qgis:latest
      
      - name: Run Tests
        run: docker run --rm --volume `pwd`:/plugin -w=/plugin qgis/qgis:latest sh -c "pip3 install -qr requirements.txt && python3 -m pytest"